eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    

microservice:
  restaurant-service:
    endpoints:
      endpoint:
        uri:http://RESTAURANT-SEARCH-SERVICE/item/id/
